[".config/tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"
refreshPeriod = "168h"

[".hammerspoon/Spoons"]
type = "archive"
url = "https://github.com/Hammerspoon/Spoons/archive/refs/heads/master.tar.gz"
stripComponents = 2
include = ["*/Spoons/RecursiveBinder.spoon.zip", "*/Spoons/EmmyLua.spoon.zip"]
refreshPeriod = "168h"
exact = true

[".vim/autoload"]
type = "archive"
url = "https://github.com/junegunn/vim-plug/archive/refs/heads/master.tar.gz"
stripComponents = 1
include = ["*/plug.vim"]

["Library/Application Support/lowfi"]
type = "archive"
url = "https://github.com/talwat/lowfi/archive/refs/heads/main.tar.gz"
stripComponents = 2
include = ["*/data/*.txt"]
refreshPeriod = "24h"

[".config/bat/themes"]
type = "archive"
url = "https://github.com/catppuccin/bat/archive/refs/heads/main.tar.gz"
stripComponents = 2
include = ["*/themes/*"]
exact = true
refreshPeriod = "168h"
